### ISSUE TITLE
How should ~/.ssh/config should look like?

### ISSUE THREAD

**Issue by grappas** [NOSDuco/remote-sshfs.nvim#1]
What syntax should I input?

**Comment by NOSDuco** [comment]
Great question, the SSH standard syntax should be used. 

You can learn more about this here: https://linuxize.com/post/using-the-ssh-config-file/ (there is loads of material on ssh configs on the internet)

I will add examples to the README.md here soon.

Let me know if this helps!

**Comment by grappas** [comment]
Thanks.
