### ISSUE TITLE
Empty argument parsing for :RemoteSSHFSConnnect

### ISSUE THREAD

**Issue by HallerPatrick** [nosduco/remote-sshfs.nvim#16]
Hey!

following the docs running `:RemoteSSHFSConnect` should bring up the telescope picker, but it doesnt for me. I am getting a `attempt to concatenate local 'remote_host' (a nil value)` error. It seems that if no argument is passed to the command `opt.args` is an empty string and tries to use it a the remote host name. 

My little fix in `init.lua` (line 51) is:
```lua
    if opts.args and opts.args ~= "" then
```

With the fix the picker is opened. If I found a bug here, I could create a PR or you could include it by yourself.  :)

Greetings,
Patrick

**Comment by nosduco** [comment]
Great catch!! Thank you so much <3 just released patch.
