### ISSUE TITLE
Make confirm window default mode to INSERT

### ISSUE THREAD

**Issue by WilliamBy** [nosduco/remote-sshfs.nvim#28]
This plugin is convenient for me. 
Though it would be appreciated if default mode of **confirm input window** could be `INSERT` .
Now it is `NORMAL` mode.

![image](https://github.com/user-attachments/assets/d975e5c3-f65b-455f-8f6b-c909948d3867)

**Comment by WilliamBy** [comment]
Btw if I manage to change input mode to `INSERT` by myself, then the mode of main window also change which is unexpected.

**Comment by nosduco** [comment]
Glad to hear! Just fixed, is on main branch now :)
