### ISSUE TITLE
Changing the mount path

### ISSUE THREAD

**Issue by Subbeh** [nosduco/remote-sshfs.nvim#7]
I can't seem to figure out how to mount any path other than the remote home directory.

Is there such an option?

**Comment by nosduco** [comment]
As of today, it mounts the default SSH directory (etc, where you would go when SSHing into the host which is usually the remote user's home directory). 

How would you like to specify where to mount? A few ideas that pop into my head are putting in the config of the plugin or a keybind in the telescope to connect a floating window to trigger an input field to where to mount or potentially another telescope floating window to select a directory.

Would love input from anyone on this!

**Comment by Subbeh** [comment]
Thanks for giving this some thought @nosduco, great project by the way.

Ideally for me, keep it simple and provide a command line option along the lines of `:RemoteSSHFSConnect <[user@]host>:/path`, and an option to list recent mounts in Telescope.

I'd love to help, but it might take a while with my limited Lua knowledge.

**Comment by nosduco** [comment]
@Subbeh Thank you for the idea!! 

I went ahead and added the command arguments like you specified above in #14 and will start working on the recent mounts for Telescope. Really helpful suggestion!
